app/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from app.views import DeleteItemView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("delete_item/", DeleteItemView.as_view(), name="delete_item"),
    path("accounts/", include("django.contrib.auth.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += debug_toolbar_urls()

kitchen/models.py
from functools import wraps
from io import BytesIO

import inflect
from django.contrib.auth.models import AbstractUser
from django.core.files.base import ContentFile
from django.db import models
from django.urls import reverse
from PIL import Image
from utility import create_route
from django.urls.exceptions import NoReverseMatch


p = inflect.engine()


def handle_no_reverse_match(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except NoReverseMatch:
            return "#"
    return wrapper


class BaseModelMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    @classmethod
    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__()
        cls.route = create_route(cls.__name__)
        cls.class_name = cls.__name__
        cls.page_name = cls.route + "-page"
        cls.plural_name = (
            p.plural(cls.class_name.lower())
             .replace(" ", "")
        )


    @handle_no_reverse_match
    def get_create_url(self):
        url = "kitchen:" + self.route + "-create"

        return reverse(url)

    @handle_no_reverse_match
    def get_update_url(self):
        url = "kitchen:" + self.route + "-update"

        return reverse(url, kwargs={"pk": self.id})

    @handle_no_reverse_match
    def get_detail_url(self):
        url = "kitchen:" + self.route + "-detail"

        return reverse(url, kwargs={"pk": self.id})

    def save(self, *args, **kwargs):
        if hasattr(self, "image") and self.image:
            img = Image.open(self.image)
            img.thumbnail((300, 300))

            buffer = BytesIO()
            img.save(buffer, format=img.format or "PNG")
            buffer.seek(0)

            self.image.save(self.image.name, ContentFile(buffer.read()), save=False)

        super().save(*args, **kwargs)


class Cook(BaseModelMixin, AbstractUser):
    years_of_experience = models.IntegerField(default=0)


class DishType(BaseModelMixin, models.Model):
    name = models.CharField(max_length=255, unique=True)
    image = models.ImageField(
        upload_to="dish_type/",
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.name


class Ingredient(BaseModelMixin, models.Model):
    name = models.CharField(max_length=255, unique=True)
    image = models.ImageField(
        upload_to="ingredient/",
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.name


class Dish(BaseModelMixin, models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    price = models.IntegerField()
    image = models.ImageField(
        upload_to="dish/",
        null=True,
        blank=True,
    )
    dish_type = models.ForeignKey(
        DishType,
        null=True,
        on_delete=models.SET_NULL,
        related_name="dishes"
    )
    ingredients = models.ManyToManyField(
        Ingredient,
        related_name="dishes",
    )
    cooks = models.ManyToManyField(
        Cook,
        related_name="dishes"
    )

templates/includes/cards/card.html
{% load custom_tags %}

<div class="card text-center">
  <div class="card-body">
    <div class="ratio ratio-1x1 rounded rounded-top border-bottom">
      <a class="d-flex align-items-center ratio ratio-1x1" href="{{ item.get_detail_url }}">
        <img id="image-preview" {% if item.image %} src="{{ item.image.url }}" {% endif %} class="card-img-top rounded-1">
      </a>
      {% if user.is_authenticated %}
      <span class="container position-absolute top-0 p-0" style="height: 2.6rem">
        <div class="row d-flex justify-content-between m-0 h-100">
          <div class="col-2 p-0 h-100" style="width: 2.6rem">
            <a href="{{ item.get_update_url }}"
               class="btn btn-success rounded-0 d-flex align-items-center justify-content-center border-0 p-0 w-100 h-100"
               style="background-color: #0c7d3e;
                      border-bottom-right-radius: var(--bs-border-radius) !important;
                      border-top-left-radius: 0.25rem !important;">
              ✏️
            </a>
          </div>
          <div class="col-2 p-0 h-100" style="width: 2.6rem">
            <button
              type="button"
              data-bs-toggle="modal"
              data-bs-target="#confirmForm"
              data-item-id="{{ item.id }}"
              data-item-class="{{ item.class_name }}"
              class="btn btn-danger rounded-0 d-flex align-items-center justify-content-center border-0 p-0 w-100 h-100"
              style="background-color: #bf0000;
                      border-bottom-left-radius: var(--bs-border-radius) !important;
                      border-top-right-radius: 0.25rem !important;">
              X
            </button>
          </div>
        </div>
      </span>
      {% endif %}
    </div>
    <a href="{{ item.get_detail_url }}">
      <h3 class="card-title m-0 mt-2">{{ item.name }}</h3>
    </a>
  </div>
</div>

templates/includes/cards/image_name_input.html
<div class="card rounded-0 rounded-top">
  <div class="card-header p-0">
    <label for="id_image" class="btn btn-secondary w-100 rounded-0 rounded-top">Set image</label>
  </div>
  <input type="file" class="form-control visually-hidden" id="id_image" accept="image/*" name="image">

  <label for="id_image">
    <div class="ratio ratio-1x1">
      {% include "includes/image_source.html" with image=form.instance.image %}
    </div>
  </label>

  <div class="card-body">
    <div class="form-floating">
      <input type="text"
             class="form-control {% include "includes/form_validate.html" with validator=form.name.errors %}"
             id="id_name"
             name="name"
             placeholder="Name..."
             value="{{ object.name }}"
             required>
      <label for="id_name">Name...</label>
    </div>
    <div class="invalid-feedback">
      {% for error in form.name.errors %}
        {{ error }}
      {% endfor %}
    </div>

  </div>
</div>
<script>
  // Get the file input and image preview elements
  const input = document.getElementById('id_image');
  const preview = document.getElementById('image-preview');

  // Event listener to handle file input changes
  input.addEventListener('change', function(event) {
    const file = event.target.files[0];
    if (file) {
      // Create a URL for the selected file and set it as the preview image source
      preview.src = URL.createObjectURL(file);
    }
  });
</script>

templates/includes/cards/image_name_readonly.html
<div class="card rounded-0">
  <div class="ratio ratio-1x1">
    {% include "includes/image_source.html" with image=object.image %}
  </div>

  <div class="card-body">
    {{ object.name }}
  </div>
</div>