app/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from app.views import DeleteItemView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("delete_item/", DeleteItemView.as_view(), name="delete_item"),
    path("accounts/", include("django.contrib.auth.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += debug_toolbar_urls()

kitchen/urls.py
import importlib
from django.urls import path

from kitchen.views import index
from kitchen.models import BaseModelMixin, Dish, DishType, Ingredient, Cook

module_name = "kitchen.views"
module = importlib.import_module(module_name)


def create_urls(model: type[BaseModelMixin]):
    class_name = model.__name__
    result = []

    try:
        list_view = getattr(module, class_name + "ListView").as_view()
        result.append(path(model.route + "/list/", list_view, name=model.route + "-list"))
    except AttributeError:
        pass

    try:
        create_view = getattr(module, class_name + "CreateView").as_view()
        result.append(path(model.route + "/create/", create_view, name=model.route + "-create"))
    except AttributeError:
        pass

    try:
        update_view = getattr(module, class_name + "UpdateView").as_view()
        result.append(path(model.route + "/update/<int:pk>/", update_view, name=model.route + "-update"))
    except AttributeError:
        pass

    try:
        detail_view = getattr(module, class_name + "DetailView").as_view()
        result.append(path(model.route + "/detail/<int:pk>/", detail_view, name=model.route + "-detail"))
    except AttributeError:
        pass

    return result

urlpatterns = [
    path("", index, name="index"),
]
urlpatterns += create_urls(Cook)
urlpatterns += create_urls(Dish)
urlpatterns += create_urls(DishType)
urlpatterns += create_urls(Ingredient)

app_name = "kitchen"

templates/includes/confirm_form.html
<div class="modal fade" id="confirmForm" tabindex="-1" aria-labelledby="confirmFormLabel" aria-hidden="true">
  <div class="modal-dialog">
    <form method="POST" action="{% url "delete_item" %}" class="modal-content">
      {% csrf_token %}
      <input type="hidden" name="item_id" id="item_id">
      <input type="hidden" name="class_name" id="class_name">
      <div class="modal-header">
        <h5 class="modal-title" id="confirmFormLabel">Do you really want to delete this item?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-footer">
        <button type="submit" class="btn btn-danger">Yes</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
      </div>
    </form>
  </div>
</div>
<script>
  // Get all delete buttons
  const deleteButtons = document.querySelectorAll('.btn-danger[data-bs-toggle="modal"]');

  // Add event listener to each delete button
  deleteButtons.forEach(button => {
    button.addEventListener('click', function () {
      const itemId = this.getAttribute('data-item-id');
      const className = this.getAttribute('data-item-class');

      document.getElementById('item_id').value = itemId;
      document.getElementById('class_name').value = className;
    });
  });
</script>

templates/includes/footer.html
<footer class="bg-body-tertiary mt-auto">
  <div class="container py-4 py-md-5 px-4 px-md-3 text-body-secondary">
      <div class="text-center">
        <span>Copyright © 2025 KitchenService</span>
      </div>
  </div>
</footer>

templates/includes/form_validate.html
{% if request.method == "POST" %}
  {% if validator %} is-invalid {% else %} is-valid {% endif %}
{% endif %}

templates/includes/image_source.html
<img id="image-preview" {% if image %} src="{{ image.url }}" {% endif %} class="card-img-top rounded-0">

templates/includes/multiple-check-buttons-readonly.html
{% load custom_tags %}

<fieldset class="h-100">
  <div class="row g-1 object-list">
  {% for item in query_for %}
    <div class="col-12">
      <button type="button" class="btn btn-primary w-100" disabled>
        <span class="text-center">{{ item|get_attribute:field }}</span>
      </button>
    </div>
  {% endfor %}
  </div>
</fieldset>

templates/includes/multiple-check-buttons.html
{% load custom_tags %}

<fieldset class="h-100">
  <div class="row g-1 object-list">
    {% for item in query_for %}
      <div class="col-12">
        <input type="checkbox"
               class="btn-check"
               name="{{ item.plural_name }}"
               value="{{ item.id }}"
               id="id_{{ item.plural_name }}_{{ item.id }}"
               autocomplete="off"
               {% if item.selected %}
                checked
               {% endif %}
        >
        <label class="btn btn-outline-primary w-100"
               for="id_{{ item.plural_name }}_{{ item.id }}">
          <span class="text-center">{{ item|get_attribute:field }}</span>
        </label>
      </div>
    {% endfor %}
  </div>
  <ul class="errorlist m-0 mt-2" id="id_cooks_error">
    {% for error in form|get_errors:query_for.model.plural_name %}
      <li>{{ error }}</li>
    {% endfor %}
  </ul>
</fieldset>

templates/includes/navbar.html
<nav class="navbar navbar-light navbar-expand
            bg-body-secondary"
>
  <div class="container">
    <a class="navbar-brand" href="{% url "kitchen:index" %}">
      KitchenService
    </a>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url "kitchen:cook-list" %}">Cooks</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "kitchen:dish-list" %}">Dishes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "kitchen:dish-type-list" %}">Dish Types</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "kitchen:ingredient-list" %}">Ingredients</a>
      </li>
    </ul>
    <div class="row">
      {% if user.is_authenticated %}
        <div class="col">
          <a class="nav-link" href="{{ user.get_absolute_url }}">@{{ user.get_username }}</a>
        </div>
        <div class="col d-flex align-items-center">
          <form action="{% url "logout" %}" method="post">
            {% csrf_token %}
            <button type="submit" class="nav-link">Logout</button>
          </form>
        </div>
      {% else %}
        <div class="col">
          <a class="nav-link" href="{% url "login" %}?next={{request.path}}">Login</a>
        </div>
      {% endif %}
    </div>
  </div>
</nav>

templates/includes/pagination.html
{% load custom_tags %}


{% with page=page|default:"page" %}
<nav>
  <ul class="pagination m-0 m-2">
    <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
      <a class="page-link" href="?{% if page_obj.has_previous %}{% query_transform page page_obj.previous_page_number %}{% endif %}">Prev</a>
    </li>
    {% for page_num in paginator.page_range %}
    <li class="page-item {% if page_obj.number == page_num %}active{% endif %}">
      <a class="page-link" href="?{% query_transform page page_num %}">{{ page_num }}</a>
    </li>
    {% endfor %}
    <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
      <a class="page-link" href="?{% if page_obj.has_next %}{% query_transform page page_obj.next_page_number %}{% endif %}">Next</a>
    </li>
  </ul>
</nav>
{% endwith %}

templates/includes/pagination_client.html
<nav>
  <ul class="pagination m-0 m-2">
    <li class="page-item">
      <button type="button" class="page-link prev-btn">Prev</button>
    </li>
    <li class="page-item">
      <button type="button" class="page-link next-btn">Next</button>
    </li>
  </ul>
</nav>